#### Task 1.1

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
type(a)

numpy.ndarray

In [4]:
b1 = a.reshape(2, 6)
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
b2 = a.reshape(3, 4)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
b3 = a.reshape(4, 3)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
b4 = a.reshape(6, 2)
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
b5 = a.reshape(12, 1)
b5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
c1 = np.reshape(a, (6, -1))
c1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
c2 = np.reshape(a, (4, -1))
c2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
c3 = np.reshape(a, (3, -1))
c3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
c4 = np.reshape(a, (-1, 6))
c4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
c5 = np.reshape(a, (-1, 4))
c5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? 
#### Наверное, нет, поскольку для доступа к любому элементу массива необходимо использовать два индекса a[1][0].

#### Task 1.2

In [22]:
a = np.random.randn(3, 4)
a

array([[-0.40857139,  0.65431138, -1.47612662,  0.67862004],
       [ 0.26595724,  1.40891701,  0.01142898, -0.56374217],
       [ 0.12105522,  0.66363089,  0.04464446, -0.01301751]])

In [26]:
b = a.flatten()
b

array([-0.40857139,  0.65431138, -1.47612662,  0.67862004,  0.26595724,
        1.40891701,  0.01142898, -0.56374217,  0.12105522,  0.66363089,
        0.04464446, -0.01301751])

In [27]:
a.size == b.size

True

#### Task 1.3

In [28]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [31]:
b = np.reshape(a, (-1, 10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

#### В чем разница между массивами a и b?
#### Массив а - одномерный, массив b = двумерный. 

#### Task 1.4

In [45]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [46]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [47]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
v.size

10

#### Task 1.5

In [49]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
A = a.reshape((4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [54]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

#### Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
#### Симметричная матрица B имеет размер 16. Обратную матрицу вычислить невозможно, поскольку ее определитель равен 0.

In [58]:
C = np.linalg.det(B)
C

0.0

#### Task 1.6

In [61]:
np.random.seed(42)

In [62]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [63]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [64]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [65]:
np.linalg.det(D)

-28511999.999999944

In [66]:
np.linalg.matrix_rank(D)

4

In [68]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#### Task 1.7

In [78]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0

In [86]:
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [87]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

In [88]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [89]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])